/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include "integerstorage.h"

//Declare integer variable to store integer values
int resultArr[1000];

//Declare integer variable to store the size of the array used.
int size = 0;


void *
append_1_svc(IntegerArray *argp, struct svc_req *rqstp)
{
	static char * result;

	/*
	 * insert server code here
	 */

	// CODE START -------------------------------------------------------------

	//FOR-LOOP to store the array from client into 'resultArr'
	for(int i = 0; i < 8 && size < 1000; i++, size++){
		//Copy the array values from the client
		resultArr[size] = argp->arr[i];
	}
	// CODE END ---------------------------------------------------------------

	return (void *) &result;
}

int *
query_1_svc(int *argp, struct svc_req *rqstp)
{
	static int  result;

	//CODE START --------------------------------------------------------------------
	//Declare a variable to store the position of value to be retrived from the array.
	int queryPosition = *argp;

	if(queryPosition < size && queryPosition >= 0){
		//retrive the value from the integer array 'resultArr' for position 'queryPosition'.
		result = resultArr[queryPosition];
	}
	else{
		result = INT_MIN;
	}
	//return result to the client
	return &result;
	//CODE END ----------------------------------------------------------------------
}

void *
remove_1_svc(int *argp, struct svc_req *rqstp)
{
	static char * result;

	//CODE START --------------------------------------------------------------------
	//Declare variable to store the position of the element in the array to be removed.
	int removeElement = *argp;

	//remove the element only if given position is less than or equal to the used array.
	if(removeElement < size){
		//Shift all the element after the postion 'removeElement' in the array 'resultArr'.
		for(int i = removeElement; i <= size; i++)
			resultArr[i] = resultArr[i+1];
		//decrease the size of the used array by 1.
		size--;
	}
	//CODE END ----------------------------------------------------------------------
	return (void *) &result;
}
