/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include "integerstorage.h"


int
integer_storage_1(char *host, char* cmd, int *arr)
{
	CLIENT *clnt;
	void  *result_1;
	IntegerArray  append_1_arg;
	int  *result_2;
	int  query_1_arg;
	void  *result_3;
	int  remove_1_arg;

#ifndef	DEBUG
	clnt = clnt_create (host, INTEGER_STORAGE, INT_STORAGE_VERS, "udp");
	if (clnt == NULL) {
		clnt_pcreateerror (host);
		exit (1);
	}
#endif	/* DEBUG */

	// CODE START----------------------------------------------
	// COMPARE STRING
	if( strcmp(cmd, "append") == 0){

		//Running for-loop to store data in integer array "arr"
		for(int i = 0; i < 8; i++)
			append_1_arg.arr[i] = arr[i];

		result_1 = append_1(&append_1_arg, clnt);
		
		if (result_1 == (void *) NULL) {
		clnt_perror (clnt, "call failed");
		}
		return 0;	
	}
	//ELSE IF condition for QUERY Function
	else if(strcmp(cmd, "query") == 0){
		//STORE POSITION OF ELEMENT TO BE RETREIVE
		query_1_arg = *arr;
		
		result_2 = query_1(&query_1_arg, clnt);
		
		if (result_2 == (int *) NULL) {
			clnt_perror (clnt, "call failed");
		}

		return *result_2;	
	}

	else if( strcmp(cmd, "remove") == 0){
		remove_1_arg = *arr;
		result_3 = remove_1(&remove_1_arg, clnt);

		if (result_3 == (void *) NULL) {
			clnt_perror (clnt, "call failed");
		}
	}

	//CODE END----------------------------------------------

#ifndef	DEBUG
	clnt_destroy (clnt);
#endif	 /* DEBUG */
}


int
main (int argc, char *argv[])
{
	//Declare host pointer variable
	char *host;

	if (argc < 2) {
		printf ("usage: %s server_host\n", argv[0]);
		exit (1);
	}
	//CODE START -------------------------------------------------------------------
	//Declared an ARRAY
	int arr[8];

	//Assign the localhost value to variable host.
	host = argv[1];
	
	//Will Execute code in th block for APPEND CONDITION
	if( strcmp(argv[2], "append") == 0){
		//FOR-LOOP for convert string to integer from command-line to variable 'arr'.
		for(int i = 0; i < 8; i++)
			arr[i] = atoi(argv[i + 3]);

		//Will display the input values
		for(int i = 0; i < 8; i++)
			printf("%i\t", arr[i]);
		printf("\n");		//New line

		//call the function 'integer_storage_1'
		integer_storage_1 (host, argv[2], arr);
	}
	//Will Execute the code in the IF BLOCK for QUERY CONDITION
	else if( strcmp(argv[2], "query" ) == 0 ){
		//Declare integer 'query'.
		int query; 
		
		//Declare integer pointer and assign reference;
		int *queryPointer = &query;
		
		//Assign value to reference refered by pointer 'queryPointer'
		*queryPointer = atoi(argv[3]);
		
		
		//call the function 'integer_storage_1' and STORE the return value of input position of the query 
		int result = integer_storage_1 (host, argv[2], queryPointer);
		
		//Check of value is retrivable
		if(result == INT_MIN)
			printf("CANNOT RETRIVE: Position is out of scope for the array.\n");
		else
			printf( "Query for position %i is %i\n", *queryPointer, result);	//PRINT the retrived value
	}
	//Will Execute the code in th IF BLOCK for REMOVE CONDITION
	else if( strcmp(argv[2], "remove" ) == 0 ){
		//Declare integer variable
		int remove; 
		
		//Declare pointer and assignt the reference
		int *removePointer = &remove;
		
		//Assign value to the space refered by the pointer
		*removePointer = atoi(argv[3]);
		
		//call the function 'integer_storage_1'
		integer_storage_1 (host, argv[2], removePointer);
	}

	//CODE END -------------------------------------------------------------------
exit (0);
}
